### Calculate Price
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "productId": "01913c04-6b58-7d9a-9fe3-76fb0a4239da",
  "taxNumber": "DE123456789",
  "couponCode": "P15"
}

### Execute Purchase
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "productId": "01913c04-6b58-7d9a-9fe3-76fb0a4239da",
  "taxNumber": "DE123456789",
  "couponCode": "P15",
  "paymentProcessor": "stripe"
}
